/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AppWorkspacesWorkspaceIdRouteImport } from './routes/_app.workspaces.$workspaceId'
import { Route as AuthLoginSplatRouteImport } from './routes/_auth.login.$'
import { Route as AuthSignupSplatRouteImport } from './routes/_auth.signup.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AppWorkspacesWorkspaceIdRoute =
  AppWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)
const AuthLoginSplatRoute = AuthLoginSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthLoginRoute,
} as any)
const AuthSignupSplatRoute = AuthSignupSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthSignupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AuthLoginRouteWithChildren
  '/signup': typeof AuthSignupRouteWithChildren
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/login/$': typeof AuthLoginSplatRoute
  '/signup/$': typeof AuthSignupSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AuthLoginRouteWithChildren
  '/signup': typeof AuthSignupRouteWithChildren
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/login/$': typeof AuthLoginSplatRoute
  '/signup/$': typeof AuthSignupSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/login': typeof AuthLoginRouteWithChildren
  '/_auth/signup': typeof AuthSignupRouteWithChildren
  '/_app/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/_auth/login/$': typeof AuthLoginSplatRoute
  '/_auth/signup/$': typeof AuthSignupSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/workspaces/$workspaceId'
    | '/login/$'
    | '/signup/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/workspaces/$workspaceId'
    | '/login/$'
    | '/signup/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/workspaces/$workspaceId'
    | '/_auth/login/$'
    | '/_auth/signup/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/workspaces/$workspaceId': {
      id: '/_app/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login/$': {
      id: '/_auth/login/$'
      path: '/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof AuthLoginSplatRouteImport
      parentRoute: typeof AuthLoginRoute
    }
    '/_auth/signup/$': {
      id: '/_auth/signup/$'
      path: '/$'
      fullPath: '/signup/$'
      preLoaderRoute: typeof AuthSignupSplatRouteImport
      parentRoute: typeof AuthSignupRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppWorkspacesWorkspaceIdRoute: typeof AppWorkspacesWorkspaceIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppWorkspacesWorkspaceIdRoute: AppWorkspacesWorkspaceIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthLoginRouteChildren {
  AuthLoginSplatRoute: typeof AuthLoginSplatRoute
}

const AuthLoginRouteChildren: AuthLoginRouteChildren = {
  AuthLoginSplatRoute: AuthLoginSplatRoute,
}

const AuthLoginRouteWithChildren = AuthLoginRoute._addFileChildren(
  AuthLoginRouteChildren,
)

interface AuthSignupRouteChildren {
  AuthSignupSplatRoute: typeof AuthSignupSplatRoute
}

const AuthSignupRouteChildren: AuthSignupRouteChildren = {
  AuthSignupSplatRoute: AuthSignupSplatRoute,
}

const AuthSignupRouteWithChildren = AuthSignupRoute._addFileChildren(
  AuthSignupRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRouteWithChildren
  AuthSignupRoute: typeof AuthSignupRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRouteWithChildren,
  AuthSignupRoute: AuthSignupRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
